Added Realm and implemented make scripts

diff --git a/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble/script/release b/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble/script/release
--- a/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble/script/release
+++ b/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble/script/release
@@ -13,6 +13,7 @@ function help {
     echo
     echo "VERSION should be the version to release, should not include the 'v' prefix"
     echo "RELEASE_NOTES should be a file that lists all the release notes for this version"
+    echo "              if file does not exist, creates a git-style commit with a diff as a comment"
     echo
     echo "FLAGS"
     echo "  -f  Forces override of tag"
@@ -79,9 +80,9 @@ fi
 if [ ! -f "$RELEASE_NOTES" ]; then
     echo " > Failed to find $RELEASE_NOTES. Prompting editor"
     RELEASE_NOTES=.release-changes
-    LATEST_TAG=`git for-each-ref refs/tags --sort=-refname --format="%(refname:short)" | grep 'v\\?\\d\\+\\.\\d\\+\\.\\d\\+' | ruby -e 'puts STDIN.read.split("\n").sort { |a,b| a.gsub("v", "").split(".").map(&:to_i) <=> b.gsub("v", "").split(".").map(&:to_i) }.last'`
+    LATEST_TAG=`git for-each-ref refs/tags --sort=-refname --format="%(refname:short)" | grep -E "^v\d+\.\d+\.\d+(-\w+(\.\d)?)?\$" | ruby -e 'puts STDIN.read.split("\n").sort { |a,b| Gem::Version.new(a.gsub(/^v/, "")) <=> Gem::Version.new(b.gsub(/^v/, "")) }.last'`
     echo " > Latest tag ${LATEST_TAG}"
-    echo "Nimble v$VERSION" > $RELEASE_NOTES
+    echo "${POD_NAME} v$VERSION" > $RELEASE_NOTES
     echo "================" >> $RELEASE_NOTES
     echo >> $RELEASE_NOTES
     echo "# Changelog from ${LATEST_TAG}..HEAD" >> $RELEASE_NOTES
@@ -130,8 +131,8 @@ echo " > Verified ownership to $POD_NAME pod"
 echo "--- Releasing version $VERSION (tag: $VERSION_TAG)..."
 
 function restore_podspec {
-    if [ -f 'Nimble.podspec.backup' ]; then
-        mv -f Nimble.podspec{.backup,}
+    if [ -f "${PODSPEC}.backup" ]; then
+        mv -f ${PODSPEC}{.backup,}
     fi
 }
 
@@ -153,7 +154,7 @@ else
         die "Failed to update version in podspec"
     }
 
-    git add Nimble.podspec || { restore_podspec; die "Failed to add Nimble.podspec to INDEX"; }
+    git add ${PODSPEC} || { restore_podspec; die "Failed to add ${PODSPEC} to INDEX"; }
     git commit -m "Bumping version to $VERSION" || { restore_podspec; die "Failed to push updated version: $VERSION"; }
 fi
 
@@ -195,5 +196,4 @@ echo "   - Paste the contents of $RELEASE_NOTES into the release notes. Tweak fo
 echo "   - Attach ${CARTHAGE_FRAMEWORK_NAME}.framework.zip to it."
 echo " - Announce!"
 
-rm Nimble.podspec.backup
-
+rm ${PODSPEC}.backup
diff --git a/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble/script/release b/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble/script/release
--- a/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble/script/release
+++ b/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble/script/release
@@ -1,5 +1,5 @@
 #!/usr/bin/env sh
-REMOTE_BRANCH=swift-2.0
+REMOTE_BRANCH=master
 POD_NAME=Nimble
 PODSPEC=Nimble.podspec
 GITHUB_TAGS_URL=https://github.com/Quick/Nimble/tags
@@ -13,6 +13,7 @@ function help {
     echo
     echo "VERSION should be the version to release, should not include the 'v' prefix"
     echo "RELEASE_NOTES should be a file that lists all the release notes for this version"
+    echo "              if file does not exist, creates a git-style commit with a diff as a comment"
     echo
     echo "FLAGS"
     echo "  -f  Forces override of tag"
@@ -65,7 +66,7 @@ if [ $? -ne 0 ]; then
 fi
 
 echo " > Is this version ($VERSION) unique?"
-git describe --exact-match "$VERSION_TAG" 2>&1 > /dev/null
+git describe --exact-match "$VERSION_TAG" > /dev/null 2>&1
 if [ $? -eq 0 ]; then
     if [ -z "$FORCE_TAG" ]; then
         die "This tag ($VERSION) already exists. Aborting. Append '-f' to override"
@@ -77,7 +78,23 @@ else
 fi
 
 if [ ! -f "$RELEASE_NOTES" ]; then
-    die "Failed to find $RELEASE_NOTES. Aborting."
+    echo " > Failed to find $RELEASE_NOTES. Prompting editor"
+    RELEASE_NOTES=.release-changes
+    LATEST_TAG=`git for-each-ref refs/tags --sort=-refname --format="%(refname:short)" | grep -E "^v\d+\.\d+\.\d+(-\w+(\.\d)?)?\$" | ruby -e 'puts STDIN.read.split("\n").sort { |a,b| Gem::Version.new(a.gsub(/^v/, "")) <=> Gem::Version.new(b.gsub(/^v/, "")) }.last'`
+    echo " > Latest tag ${LATEST_TAG}"
+    echo "${POD_NAME} v$VERSION" > $RELEASE_NOTES
+    echo "================" >> $RELEASE_NOTES
+    echo >> $RELEASE_NOTES
+    echo "# Changelog from ${LATEST_TAG}..HEAD" >> $RELEASE_NOTES
+    git log ${LATEST_TAG}..HEAD | sed -e 's/^/# /' >> $RELEASE_NOTES
+    $EDITOR $RELEASE_NOTES
+    diff -q $RELEASE_NOTES ${RELEASE_NOTES}.backup > /dev/null 2>&1
+    STATUS=$?
+    rm ${RELEASE_NOTES}.backup
+    if [ $STATUS -eq 0 ]; then
+        rm $RELEASE_NOTES
+        die "No changes in release notes file. Aborting."
+    fi
 fi
 echo " > Release notes: $RELEASE_NOTES"
 
@@ -114,8 +131,8 @@ echo " > Verified ownership to $POD_NAME pod"
 echo "--- Releasing version $VERSION (tag: $VERSION_TAG)..."
 
 function restore_podspec {
-    if [ -f 'Nimble.podspec.backup' ]; then
-        mv -f Nimble.podspec{.backup,}
+    if [ -f "${PODSPEC}.backup" ]; then
+        mv -f ${PODSPEC}{.backup,}
     fi
 }
 
@@ -128,7 +145,8 @@ $CARTHAGE build --no-skip-current || die "Failed to build framework for carthage
 
 echo "-> Setting podspec version"
 cat "$PODSPEC" | grep 's.version' | grep -q "\"$VERSION\""
-if [ $? -eq 0 ]; then
+SET_PODSPEC_VERSION=$?
+if [ $SET_PODSPEC_VERSION -eq 0 ]; then
     echo " > Podspec already set to $VERSION. Skipping."
 else
     sed -i.backup "s/s.version *= *\".*\"/s.version      = \"$VERSION\"/g" "$PODSPEC" || {
@@ -136,10 +154,8 @@ else
         die "Failed to update version in podspec"
     }
 
-    git add Nimble.podspec || { restore_podspec; die "Failed to add Nimble.podspec to INDEX"; }
+    git add ${PODSPEC} || { restore_podspec; die "Failed to add ${PODSPEC} to INDEX"; }
     git commit -m "Bumping version to $VERSION" || { restore_podspec; die "Failed to push updated version: $VERSION"; }
-    git push origin "$REMOTE_BRANCH" || die "Failed to push to origin"
-    echo " > Pushed version to origin"
 fi
 
 if [ -z "$FORCE_TAG" ]; then
@@ -152,6 +168,12 @@ else
     git tag -f -s "$VERSION_TAG" -F "$RELEASE_NOTES" || die "Failed to tag version"
     echo "-> Pushing tag to origin (force)"
     git push origin "$VERSION_TAG" -f || die "Failed to push tag '$VERSION_TAG' to origin"
+fi
+
+if [ $SET_PODSPEC_VERSION -ne 0 ]; then
+    rm $RELEASE_NOTES
+    git push origin "$REMOTE_BRANCH" || die "Failed to push to origin"
+    echo " > Pushed version to origin"
 fi
 
 echo
@@ -174,5 +196,4 @@ echo "   - Paste the contents of $RELEASE_NOTES into the release notes. Tweak fo
 echo "   - Attach ${CARTHAGE_FRAMEWORK_NAME}.framework.zip to it."
 echo " - Announce!"
 
-rm Nimble.podspec.backup
-
+rm ${PODSPEC}.backup
